export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";

export const FETCH_SINGLE_QUESTION = "FETCH_SINGLE_QUESTION";
export const FETCH_SINGLE_QUESTION_ERROR = "FETCH_SINGLE_QUESTION_ERROR";
export const FETCH_SINGLE_QUESTION_SUCCESS = "FETCH_SINGLE_QUESTION_SUCCESS";
