export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_  ERROR";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";

export const FETCH_QUESTION_DETAILS = "FETCH_QUESTION_DETAILS";
export const FETCH_QUESTION_DETAILS_ERROR = "FETCH_QUESTION_DETAILS_ERROR";
export const FETCH_QUESTION_DETAILS_SUCCESS = "FETCH_QUESTION_DETAILS_SUCCESS";

export const QUESTION_VOTE = "QUESTION_VOTE";
export const QUESTION_VOTE_ERROR = "QUESTION_VOTE_ERROR";
export const QUESTION_VOTE_SUCCESS = "QUESTION_VOTE_SUCCESS";
