export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";

export const FETCH_QUESTION_DETAILS = "FETCH_QUESTION_DETAILS";
export const FETCH_QUESTION_DETAILS_ERROR = "FETCH_QUESTION_DETAILS_ERROR";
export const FETCH_QUESTION_DETAILS_SUCCESS = "FETCH_QUESTION_DETAILS_SUCCESS";
